HTFTP (Handicapped Transfer File Transfer Protocol) - is a simple rfc1350 based protocol that works on UDP/IP. This is very much similar to TFTP protocol - only lighter - as you might have guessed :-)
For the sake of this protocol, there are only 2 type of peers:
- Sender (the one that sends a file)
- Receiver (take a guess)

*** Overview

**** General
It may be used to transfer files between two systems. In brief:

- Any transfer begins with a request write a file. This request also serves to request a connection. The Sender would request the connection.
- If the Receiver grants the request, the connection is opened.
- The file is sent in fixed length blocks of 512 bytes(default).
- Each data packet contains one block of data, and must be acknowledged by the Receiver before the next packet can be sent.
- Receiver must send these acknowledgment packets to the sender.
- A data packet of less than 512 bytes signals termination of a transfer.
- If a packet gets lost in the network, the intended Receiver will timeout and may retransmit his last packet (which may be data or an acknowledgment), thus causing the sender of the lost packet to retransmit that lost packet.
- The Sender has to keep just one packet on hand for retransmission, since the lock step acknowledgment guarantees that all older packets have been received.

**** Packet Types
HTFTP supports the following packet types

***** Init-Request Packet(IRQ)
Can only be sent by the Sender.
***** Data Packet
Can only be sent by the Sender.
***** Acknowledgment Packet(ACK)
Can only be sent by the Receiver.
***** Error Packet
An error is signalled by sending an error packet.  This packet is not acknowledged, and not retransmitted.
There are 3 types of errors:
file not found, access violation, disk full

*** Connection Establishment

A transfer is established by sending a request (WRQ to write onto a
foreign file system, or RRQ to read from it), and receiving a
positive reply, an acknowledgment packet for write, or the first data
packet for read.  In general an acknowledgment packet will contain
the block number of the data packet being acknowledged.

***
